# Generated by Django 4.2.2 on 2023-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forums", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
